name = "techy-email-inbox"
main = "worker.js"
compatibility_date = "2026-08-09"
compatibility_flags = ["nodejs_compat"]
account_id = "4373c9cc85d5918cdc74ddf90bd31b63"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "techy-db"
database_id = "8fcbea87-08e4-4df1-b145-222db8b8dd20"
